channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - numpy==2.0.2
  - pandas==2.2.3
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.15.1
  - unidecode==1.4.0
name: mlflow-env
